name: Check Ticket Availability
on:
  schedule:
    - cron: '*/15 * * * *'  # Runs the workflow every 15 minutes

jobs:
  check_availability:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: pip install beautifulsoup4 requests
      
    - name: Run script
      run: python CPHHALF_bot.py
      env:
        SLACK_HOOK: ${{ secrets.SLACK_HOOK }}
      