name: Check Ticket Availability

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs the workflow every 5 minutes

jobs:
  run_script:
    name: Run Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python CPHHALF_bot.py
        env:
          PYTHONPATH: ./CPHHALF_bot.py  # Set the Python script's path as an environment variable
          WEBHOOK_URL: ${{ secrets.SLACK_HOOK }}